name: 'Find Slack User'
description: 'GitHub Action to find a Slack user data by email.'
branding:
  icon: 'user'
  color: 'blue'
inputs:
  email:
    description: 'Email'
    required: true
  fields:
    description: 'The fields you want to get in the response'
    required: true
outputs:
  user:
    description: 'The Slack user data'
runs:
  using: 'node16'
  main: 'dist/index.js'
